# Generated by Django 6.0.4 on 2026-06-19 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW_BID', 'New bid'), ('BID_ACCEPTED', 'Bid accepted'), ('BID_REJECTED', 'Bid rejected'), ('CONTRACT_CREATED', 'Contract created'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_COMPLETED', 'Payment completed'), ('PROJECT_STARTED', 'Project started'), ('PROJECT_COMPLETED', 'Project completed'), ('CONTRACT_FINISHED', 'Contract finished'), ('REVIEW_CREATED', 'Review created'), ('DEADLINE_WARNING', 'Deadline warning'), ('MESSAGE_RECEIVED', 'Message received')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contract.contract')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='project.project')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
